### ISSUE TITLE
.flutter_settings : support non-string json values

### ISSUE THREAD

**Issue by benoitskipr** [bitrise-steplib/bitrise-step-flutter-build#12]
hi, the `.flutter_settings` file can contain values different than strings, like booleans,
```{
  "ios-signing-cert": "iPhone Developer: benoit@***.com (92RAR46KUA)",
  "enable-web": true
}
```
but the parsing does not take that into account atm, so I get a `Failed to unmarshal .flutter_settings file, error: json: cannot unmarshal bool into Go value of type string`

https://github.com/bitrise-steplib/bitrise-step-flutter-build/blob/acfbae87b8c6831bf59303eead40a389977b6fae/main.go#L113

sry I don't know Go enough to fix it myself

**Comment by bitce** [comment]
Hi @benoitskipr!

Thanks for reporting! Could you also send us an URL for a build where this occurs?

**Comment by alexshikov** [comment]
To reproduce the issue switch to flutter beta channel, enable the web support and run local bitrise run:

```bash
flutter channel beta
flutter upgrade
flutter config --enable-web

bitwise run
```
