### ISSUE TITLE
None of the environment variables are being exported

### ISSUE THREAD

**Issue by humblerookie** [bitrise-steplib/bitrise-step-flutter-build#15]
I've included this step, post apk generation I echo'ed for the output environment variables but none of them seem set and a subsequent step that depends on this environment variable was also failing.

`$BITRISE_APK_PATH` is not set and neither are the `$BITRISE_APK_PATH_LIST` and other variables.  I'm using the `0.12.0` version. 

What am I missing? Do let me know if you need more info

**Comment by bitce** [comment]
Hi @humblerookie!

Sorry to hear about this. Can you please send us an URL for a build where this is happening?

**Comment by humblerookie** [comment]
@bitce  This. https://app.bitrise.io/build/540cadc3284caa3a#?tab=log
I had to add a custom step after the build that explicitly exported the environment var of `BITRISE_APK_PATH` to value of ` ENV[''BITRISE_DEPLOY_DIR'']+''/app-release.apk'`. Hope this helps.

**Comment by humblerookie** [comment]
Any updates? @bitce

**Comment by ahvth-bitrise** [comment]
Hi @humblerookie! Just wanted to let you know that we think this is an issue with the step that may need to be fixed on our end. Our tooling team is currently investigating. Thanks so much for reaching out! 😄

**Comment by bitce** [comment]
Hi @humblerookie!

Sorry for the huge delay. There has been a lot of changes and improvements since you raised this thread, we wanted to reach out to ask if you can still reproduce the problem? If so, sharing the steps how to would be really useful to us, as we can not at this moment.

**Comment by humblerookie** [comment]
Hi @bitce ,
I'll take a look and let you know.

**Comment by bitce** [comment]
Hi again @humblerookie!

Please do so if you have the time, the development team is looking at the task and we'd like to understand if we have to move forward here.

**Comment by humblerookie** [comment]
Sorry about the delayed response @bitce. This is working now thank you.
