### ISSUE TITLE
Build starts immediately even when "Enable manual build approval option" is set

### ISSUE THREAD

**Issue by mark-veenstra** [bitrise-steplib/bitrise-step-flutter-build#19]
Hi,

We would like to approve builds on PR changes provided by forks. Therefore we enabled the option: "Enable manual build approval option".  Like so:

![image](https://user-images.githubusercontent.com/8984015/82412722-7222f980-9a74-11ea-94e5-bb896b58e90b.png)

But once a fork submits changes the build is started directly instead of the need of approval. See: https://app.bitrise.io/build/24506030a2a538d8#?tab=log

For now I made the trigger only to response to a specific source branch so forks can't start any builds at the moment.

Any idea?

Mark

**Comment by Roland-Bak** [comment]
Hey there @mark-veenstra 🙂

Could you please clarify if the build is started when a Pull Request is made, or when it has been accepted and has been merged into the target branch?

I think the root of the issue is that the 'Enable manual build approval option' is for Pull Requests, but merging into a branch counts as a Push regarding the Bitrise triggers.

**Comment by mark-veenstra** [comment]
Well what I am trying to accomplish with Bitrise and our opensource plugin is as follows:

Changes made with MR/PR *not* from a forked repository (which means changes applied through MR/PR from known authorized developers):
* Workflow on Bitrise should be triggered on MR/PR changes
* A known and authorized developer creates a MR/PR on GitLab. This MR/PR has a feature source branch and master as target branch.
* When this developer pushes changes to the source branch, the trigger of a changing MR/PR should trigger the workflow without any approvals

Changes made with MR/PR from a forked repository (which means changes applied through MR/PR from unknown developers with potential of stealing stuff):
* Workflow on Bitrise should be triggered on MR/PR changes (but needs approvals)
* An unknown developer creates a MR/PR on GitLab. This MR/PR has a feature source branch from forked repository and master as target branch.
* When this developer pushes changes to the forked source branch, the trigger of a changing MR/PR should trigger the workflow but with approvals to start the build.
* We can now investigate the source code and ones we validated it we can start the build manually by approving it.

Hope this makes it clear. If not I am happy to share more information.
