### ISSUE TITLE
Add support for macOS, Linux and web builds

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [bitrise-steplib/bitrise-step-flutter-build#27]
Now, as Flutter officially supports macOS, the web and Linux, it would be great to have them available for build too. Maybe Linux will be a bit difficult to implement (as builds run on macOS) but web and macOS should be quite easy to support.

**Comment by bitce** [comment]
Thanks for the feature request @TheOneWithTheBraid!

**Comment by TheOneWithTheBraid** [comment]
Is there any effort or any plan to support non-mobile builds?

**Comment by TheOneWithTheBraid** [comment]
Still important.

**Comment by mefiblogger** [comment]
Hello,

It's Mefi here from the Bitrise CoreSteps Team. Thanks for reaching out helping us and the mobile community to have a better experience with Bitrise steps. 💜

We started to have a broader review of all the open issues and PRs and we are continuously prioritizing these in our sprints.

We reviewed this issue and we found it to be a valid feature request. We are collecting new feature requests on our [Discuss forum](https://discuss.bitrise.io/c/feature-request/) where you can upvote and discuss further details. As this one is on our current roadmap, I close the issue and we'll share an update once we released the new version of the step. Until then, feel free to create a feature request and share your thoughts on Discuss.

Happy building! 🚀
