### ISSUE TITLE
Flutter Build step does not work on Xcode 15

### ISSUE THREAD

**Issue by smmcdonald** [bitrise-steplib/bitrise-step-flutter-build#49]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 0.17.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

This has been issue has been identified to be related to CocoaPods and is fixed in a more recent version of CocoaPods. It's likely all that is needed to fix this is to update the version of CocoaPods this step uses.
https://github.com/CocoaPods/CocoaPods/issues/12012

### Issue description

When building Flutter projects on the Xcode 15 stack, the Flutter Build step fails with error:
`Failed to build iOS app
Error (Xcode): DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead`

### Bitrise info

- Build URL: [_Please share the build URL with us._](https://app.bitrise.io/build/6c2bb148-ce97-4a0c-810e-8eb61a181c0a)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: NO
- Log: 

<details>
  <pre>
 Failed to build iOS app
Error (Xcode): DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead
  </pre>
</details>

### Steps to reproduce

1. Set the workflow build stack to use M1 Silicon and Xcode 15
2. Build a Flutter project workflow that uses the flutter-build Bitrise step

**Comment by EBaglieriSkylabs** [comment]
Same issue

**Comment by deffs** [comment]
@godrei any updates on this? This is a block us from using the new Xcode 15 stacks and we don't want to fall too far behind.

**Comment by deffs** [comment]
@EBaglieriSkylabs looks like Bitrise recommended adding this code to the Podfile to resolve this issue:

<img width="745" alt="image" src="https://github.com/bitrise-steplib/bitrise-step-flutter-build/assets/26584313/891020f8-9ab4-4254-b3c0-2261218ae807">

**Comment by deffs** [comment]
Any updates on this? Looks like Apple is deprecating Xcode 14 stacks in April.

**Comment by EBaglieriSkylabs** [comment]
I resolved time ago inserting a script step before "Flutter build" with this content:
```bash
#!/usr/bin/env bash
# fail if any commands fails
set -e
# make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
set -o pipefail
# debug log
set -x

#Cocoapods
export GEM_HOME=$HOME/.gem/ruby/3.2.0
export PATH=$GEM_HOME/bin:$PATH
gem install cocoapods -v 1.14.3 --user-install
```

<img width="376" alt="Screenshot 2024-02-08 alle 19 49 02" src="https://github.com/bitrise-steplib/bitrise-step-flutter-build/assets/129297102/ccd8b9b1-a214-45b7-8e55-15f21c2e1e99">
