### ISSUE TITLE
Add support for newer Java version 

### ISSUE THREAD

**Issue by Mounix99** [bitrise-steplib/bitrise-step-flutter-build#52]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected?  -` Version 0.17.0` 
- Is the issue reproducible with the latest version? `YES` 
- Does the issue happen sporadically, or every time? `EVERY TIME`
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES / NO / NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

It is impossible to build Flutter project with some version of packages, (issue related not only to Flutter). Some project requires Newer Java version 
Execution failed for task ':stripe_android:compileReleaseJavaWithJavac'.
  error: invalid source release: 17

### Bitrise info

- Build URL: [build] (https://app.bitrise.io/build/76fef3b6-3bcd-4fbf-8f64-2496b0ae0583)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: `YES `
- Log: 

<details>
  <pre>
* What went wrong:
Execution failed for task ':stripe_android:compileReleaseJavaWithJavac'.
> error: invalid source release: 17
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org/
BUILD FAILED in 8m 18s
Running Gradle task 'assembleStagingRelease'...                   500.9s
Gradle task assembleStagingRelease failed with exit code 1
Run: failed to build Android app: exit status 1
Run: failed to build Android app: exit status 1
  </pre>
</details>

### Steps to reproduce

1. Try latest version of [Stripe package](https://pub.dev/packages/flutter_stripe) for Flutter

**Comment by serdar-coskun** [comment]
I have the same problem

**Comment by Mounix99** [comment]
Any updates?

**Comment by hautvfami** [comment]
same for me

**Comment by Mounix99** [comment]
Can anyone look into it or at least create a fork ?

**Comment by Mounix99** [comment]
@ofalvai can you help here? It doesn't seems to be something big to deal with...

**Comment by ofalvai** [comment]
JDK 17 has been available on all Bitrise stacks for a while, even though that's not the default version on some stacks. I know it's a bit confusing, but here is the current state of the stacks as of today:

- Ubuntu 20: JDK 11 is the default, JDK 17 is also installed
- Ubuntu 22: JDK 17 is the default, JDK 11 and 21 also installed
- Xcode 14.x and 15.x (stable) stacks: JDK 11 is the default, JDK 17 and 21 also installed
- Xcode 16 (edge) stack: JDK 17 is the default, JDK 11 and 21 also installed

If you want to switch the active version in a build, you can do that with the Set Java version step, it works across all stacks.

Also, for future reference, we publish an overview of tool versions across the stacks, this is the one for JDK: https://stacks.bitrise.io/tools/java/

**Comment by Mounix99** [comment]
Thank you @ofalvai for detailed explanation! 
for everyone who requires docs about manual Java version changing: https://devcenter.bitrise.io/en/infrastructure/build-stacks/managing-java-versions.html
