### ISSUE TITLE
Support for Android App Bundles

### ISSUE THREAD

**Issue by g123k** [bitrise-steplib/bitrise-step-flutter-build#6]
Hello,

Since the 1.2.1 stable release, Flutter is now able to produce Android App Bundles (*.aab files), instead of just apks. It would be great if we could choose between an apk and an aab during the build phrase.

```
flutter build appbundle
```

Thanks again for your amazing work!

**Comment by bitce** [comment]
Hi @g123k 

Thanks for raising this question! We, of course, would love to provide as much support as much options as possible! The reason we are not currently working on this is due to the feature being really new and it lacks any kind of documentation. (Please see: https://github.com/flutter/flutter/issues/17829#issuecomment-468607923) 

Once that changes, we'll be looking into it! :)

**Comment by maxlapides** [comment]
@bitce you can see some documentation by running `flutter build appbundle --help`

```
❯ flutter build appbundle --help
Build an Android App Bundle file from your app.

This command can build debug and release versions of an app bundle for your application. 'debug' builds support debugging and a quick development cycle. 'release' builds don't support debugging and are suitable
for deploying to app stores.
 app bundle improves your app size

Usage: flutter build appbundle [arguments]
-h, --help                    Print this usage information.
-t, --target=<path>           The main entry-point file of the application, as run on the device.
                              If the --target option is omitted, but a file name is provided on the command line, then that is used instead.
                              (defaults to "lib/main.dart")

    --debug                   Build a debug version of your app.
    --profile                 Build a version of your app specialized for performance profiling.
    --release                 Build a release version of your app (default mode).
    --flavor                  Build a custom app flavor as defined by platform-specific build setup.
                              Supports the use of product flavors in Android Gradle scripts.
                              Supports the use of custom Xcode schemes.

    --[no-]pub                Whether to run "flutter packages get" before executing this command.
                              (defaults to on)

    --build-number            An identifier used as an internal version number.
                              Each build must have a unique identifier to differentiate it from previous builds.
                              It is used to determine whether one build is more recent than another, with higher numbers indicating more recent build.
                              On Android it is used as 'versionCode'.
                              On Xcode builds it is used as 'CFBundleVersion'

    --build-name=<x.y.z>      A "x.y.z" string used as the version number shown to users.
                              For each new version of your app, you will provide a version number to differentiate it from previous versions.
                              On Android it is used as 'versionName'.
                              On Xcode builds it is used as 'CFBundleShortVersionString'

    --build-shared-library    Whether to prefer compiling to a *.so file (android only).
    --target-platform         [android-arm (default), android-arm64]
```

Is there any more information that you need to support this feature?

**Comment by bitce** [comment]
Hi @maxlapides, thanks for pointing this out! The situation is indeed a bit more complicated but this is definitely on our roadmap, that said a built-in support for native Android apps is more of a priority initially.

**Comment by maxlapides** [comment]
@bitce Okay thanks! Just so you know, Google Play has now enabled warnings that alert you to build your app with Android App Bundle when you prepare a release, so until this issue is resolved all users of this workflow step will be getting this somewhat confusing warning on Google Play.

**Comment by guitcastro** [comment]
This really needs to be prioritized. It's already on the official documented on the flutter docs:

https://flutter.dev/docs/deployment/android#building-a-release-app-bundle

I am not able to release alpha/beta APKs

**Comment by bitce** [comment]
Hi @guitcastro! Thanks for sharing! To be blunt, we are  working on making our regular flutter support more efficient before taking on this. I understand a lot of you may have understood that we are not doing this solely for the lack of documentation, that is not the case entirely. As far as I understand flutter is still only able to build only one target platform at a time, so this is in an investigation state from us still.

In case you are eager to see this in Bitrise please move your request here: https://discuss.bitrise.io/c/feature-request

Thanks for all your understanding and patience!

**Comment by maxlapides** [comment]
It looks like the App Bundle support has just landed in Flutter on the beta channel. I am now getting this warning:

```
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
```

@bitce do you have an update on when Bitrise will support App Bundles? Should I attempt to split the APKs per ABI?

**Comment by bitce** [comment]
Hi @maxlapides, sorry, still no ETA yet unfortunately. We'll make absolutely sure to let you know here once there is an update to provide.

**Comment by koral--** [comment]
Here is a PR with AAB support: https://github.com/bitrise-steplib/bitrise-step-flutter-build/pull/8
New input `android_output_type` is added. It defaults to `apk` for backwards compatibility but can be switched to `appbundle`

**Comment by anatter** [comment]
@bitce please merge this ASAP

**Comment by ahvth-bitrise** [comment]
> @bitce please merge this ASAP

koral's PR is currently queued for review 👍
